# Outputting
permalink: articles/:year/:month/:day/:title/

# Conversion
markdown: kramdown
highlighter: pygments
excerpt_separator: "<!---more--->"

# Serving
baseurl:  /dovetail-automata.github.io
host: 0.0.0.0  # attach to all IP addresses
port: 8080  # 4000 used by NFS!

# Variable defaults
defaults:
  -
    scope:
      path: ""
    values:
      author:  "zultron"

# Custom vars
#
# Used in title
name: Dovetail Automata
# Used in analytics.html
url: http://zultron.github.io/dovetail-automata.github.io
google_analytics_id: 'put_your_google_analytics_id_here'
# Used in head.html
repository: https://github.com/zultron/dovetail-automata.github.io
